/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ActionComponent {
    }
    interface ExampleComponent {
        "exampleProp": string;
    }
}
declare global {
    interface HTMLActionComponentElement extends Components.ActionComponent, HTMLStencilElement {
    }
    var HTMLActionComponentElement: {
        prototype: HTMLActionComponentElement;
        new (): HTMLActionComponentElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "action-component": HTMLActionComponentElement;
        "example-component": HTMLExampleComponentElement;
    }
}
declare namespace LocalJSX {
    interface ActionComponent {
    }
    interface ExampleComponent {
        "exampleProp"?: string;
    }
    interface IntrinsicElements {
        "action-component": ActionComponent;
        "example-component": ExampleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "action-component": LocalJSX.ActionComponent & JSXBase.HTMLAttributes<HTMLActionComponentElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
        }
    }
}
